In [1]:
#Import necessary library
import numpy as np
import pandas as pd

In [3]:
#Import sklearn load dataset
from sklearn.datasets import load_iris
iris_dataset=load_iris()

In [4]:
#Display the dataset type
type(iris_dataset)

sklearn.utils.Bunch

In [6]:
#View the information of the dataset using DESCR (describe)
print(iris_dataset['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [8]:
#View features
iris_dataset.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [12]:
#View target (response)
iris_dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
#Find the number of observations
iris_dataset.data.shape

(150, 4)

In [14]:
#Assign features to X axis
X_features=iris_dataset.data

In [15]:
#Assign target data to Y axis
Y_target=iris_dataset.target

In [18]:
#View the shape of both the axes
print('X Axis:',X_features.shape)
print('Y Axis:',Y_target.shape)

X Axis: (150, 4)
Y Axis: (150,)


In [19]:
#First use the KNN classifier method - import it from sklearn
from sklearn.neighbors import KNeighborsClassifier

In [20]:
#instantiate the KNN estimator
knn=KNeighborsClassifier(n_neighbors=1)

In [25]:
#Print knn
print(knn)

KNeighborsClassifier(n_neighbors=1)


In [27]:
#Fit the data into the KNN model (estimator)
knn.fit(X_features,Y_target)

KNeighborsClassifier(n_neighbors=1)

In [28]:
#Create object with new values for prediction
X_new=[[3,5,4,1],[5,3,4,2]]

In [29]:
#Predict the outcome for the new observation using knn classifier
knn.predict(X_new)

array([1, 1])

In [31]:
#Use logistic regression estimator
from sklearn.linear_model import LogisticRegression
logreg=LogisticRegression()

In [33]:
#Fit data into the logistic regression estimator
logreg.fit(X_features,Y_target)

/usr/local/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [35]:
#Predict the outcome using Logistic regression estimator
logreg.predict(X_new)

array([0, 1])