In [1]:
#import required libraries and dataset
from sklearn.datasets import load_iris
iris_dataset=load_iris()

In [2]:
#View feature names of the dataset
iris_dataset['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [3]:
iris_dataset.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [4]:
#view target of the dataset
iris_dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
#define feature and target objects
x_feature=iris_dataset.data
y_target=iris_dataset.target

In [6]:
#create object with new values for prediction
x_new=[[3,5,4,1],[5,3,4,2]]

In [12]:
#use the logistic regression estimator
from sklearn.linear_model import LogisticRegression
logreg=LogisticRegression()

In [13]:
#fit data into the logistic regression estimator
logreg.fit(x_feature,y_target)

/usr/local/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [15]:
#predict the outcome usinglogistic regression estimator
logreg.predict(x_new)

array([0, 1])

In [20]:
#import library for model persistence
import pickle as pkl

In [22]:
#Use dumps method to persist the model
persist_model=pkl.dumps(logreg)
persist_model

b'\x80\x03csklearn.linear_model._logistic\nLogisticRegression\nq\x00)\x81q\x01}q\x02(X\x07\x00\x00\x00penaltyq\x03X\x02\x00\x00\x00l2q\x04X\x04\x00\x00\x00dualq\x05\x89X\x03\x00\x00\x00tolq\x06G?\x1a6\xe2\xeb\x1cC-X\x01\x00\x00\x00Cq\x07G?\xf0\x00\x00\x00\x00\x00\x00X\r\x00\x00\x00fit_interceptq\x08\x88X\x11\x00\x00\x00intercept_scalingq\tK\x01X\x0c\x00\x00\x00class_weightq\nNX\x0c\x00\x00\x00random_stateq\x0bNX\x06\x00\x00\x00solverq\x0cX\x05\x00\x00\x00lbfgsq\rX\x08\x00\x00\x00max_iterq\x0eKdX\x0b\x00\x00\x00multi_classq\x0fX\x04\x00\x00\x00autoq\x10X\x07\x00\x00\x00verboseq\x11K\x00X\n\x00\x00\x00warm_startq\x12\x89X\x06\x00\x00\x00n_jobsq\x13NX\x08\x00\x00\x00l1_ratioq\x14NX\x0e\x00\x00\x00n_features_in_q\x15K\x04X\x08\x00\x00\x00classes_q\x16cnumpy.core.multiarray\n_reconstruct\nq\x17cnumpy\nndarray\nq\x18K\x00\x85q\x19C\x01bq\x1a\x87q\x1bRq\x1c(K\x01K\x03\x85q\x1dcnumpy\ndtype\nq\x1eX\x02\x00\x00\x00i8q\x1f\x89\x88\x87q Rq!(K\x03X\x01\x00\x00\x00<q"NNNJ\xff\xff\xff\xffJ\xff\xff\x

In [24]:
#Use joblib.dump to persist the model to a file
import joblib
joblib.dump(logreg,'regresfilename.pkl')

['regresfilename.pkl']

In [28]:
#Use joblib.load to persist the model to a file
#Creat new estimator from the saved model
new_logreg_estimator=joblib.load('regresfilename.pkl')

In [33]:
#View the new estimator
new_logreg_estimator

LogisticRegression()

In [34]:
#Validate and use new estimator to predict
new_logreg_estimator.predict(x_new)

array([0, 1])

In [35]:
#A model can be created, trained and persisted for future use